apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq:3
  namespace: roboshop
   # these are replica set labels
  labels:
    project: roboshop
    component: rabbitmq:3
    tier: db
spec:
  replicas: 1
  selector:
  # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: rabbitmq:3
      tier: db
  # pod definition    
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq:3
        tier: db
    spec:
      containers:
      - name: rabbitmq:3
        image: rabbitmq:3:7.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 5
    

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq:3
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq:3
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port
  